import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen bg-gradient-to-br from-gray-200 to-yellow-100 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto mt-2 space-y-3">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
